#set_property IOSTANDARD LVCMOS33 [get_ports clk]
#set_property IOSTANDARD LVCMOS33 [get_ports rst]
#set_property PACKAGE_PIN P17 [get_ports clk]
#set_property PACKAGE_PIN T5 [get_ports rst]

#set_property IOSTANDARD LVCMOS33 [get_ports sure_btn1]
#set_property PACKAGE_PIN R15 [get_ports sure_btn1]

#set_property IOSTANDARD LVCMOS33 [get_ports x0]
#set_property IOSTANDARD LVCMOS33 [get_ports x1]
#set_property IOSTANDARD LVCMOS33 [get_ports x2]
#set_property PACKAGE_PIN V2 [get_ports x0]
#set_property PACKAGE_PIN U2 [get_ports x1]
#set_property PACKAGE_PIN U3 [get_ports x2]

#set_property IOSTANDARD LVCMOS33 [get_ports sw7]
#set_property IOSTANDARD LVCMOS33 [get_ports sw6]
#set_property IOSTANDARD LVCMOS33 [get_ports sw5]
#set_property IOSTANDARD LVCMOS33 [get_ports sw4]
#set_property IOSTANDARD LVCMOS33 [get_ports sw3]
#set_property IOSTANDARD LVCMOS33 [get_ports sw2]
#set_property IOSTANDARD LVCMOS33 [get_ports sw1]
#set_property IOSTANDARD LVCMOS33 [get_ports sw0]
#set_property PACKAGE_PIN P5 [get_ports sw7]
#set_property PACKAGE_PIN P4 [get_ports sw6]
#set_property PACKAGE_PIN P3 [get_ports sw5]
#set_property PACKAGE_PIN P2 [get_ports sw4]
#set_property PACKAGE_PIN R2 [get_ports sw3]
#set_property PACKAGE_PIN M4 [get_ports sw2]
#set_property PACKAGE_PIN N4 [get_ports sw1]
#set_property PACKAGE_PIN R1 [get_ports sw0]

#set_property IOSTANDARD LVCMOS33 [get_ports scene1_btn]
#set_property PACKAGE_PIN V1 [get_ports scene1_btn]
#set_property IOSTANDARD LVCMOS33 [get_ports scene2_btn]
#set_property PACKAGE_PIN R11 [get_ports scene2_btn]

#set_property IOSTANDARD LVCMOS33 [get_ports scene1_lt]
#set_property PACKAGE_PIN K3 [get_ports scene1_lt]
#set_property IOSTANDARD LVCMOS33 [get_ports scene2_lt]
#set_property PACKAGE_PIN M1 [get_ports scene2_lt]

#set_property IOSTANDARD LVCMOS33 [get_ports lt7]
#set_property IOSTANDARD LVCMOS33 [get_ports lt6]
#set_property IOSTANDARD LVCMOS33 [get_ports lt5]
#set_property IOSTANDARD LVCMOS33 [get_ports lt4]
#set_property IOSTANDARD LVCMOS33 [get_ports lt3]
#set_property IOSTANDARD LVCMOS33 [get_ports lt2]
#set_property IOSTANDARD LVCMOS33 [get_ports lt1]
#set_property IOSTANDARD LVCMOS33 [get_ports lt0]
#set_property PACKAGE_PIN F6 [get_ports lt7]
#set_property PACKAGE_PIN G4 [get_ports lt6]
#set_property PACKAGE_PIN G3 [get_ports lt5]
#set_property PACKAGE_PIN J4 [get_ports lt4]
#set_property PACKAGE_PIN H4 [get_ports lt3]
#set_property PACKAGE_PIN J3 [get_ports lt2]
#set_property PACKAGE_PIN J2 [get_ports lt1]
#set_property PACKAGE_PIN K2 [get_ports lt0]

#set_property IOSTANDARD LVCMOS33 [get_ports light]
#set_property PACKAGE_PIN K1 [get_ports light]

#set_property IOSTANDARD LVCMOS33 [get_ports sure_lt]
#set_property PACKAGE_PIN L1 [get_ports sure_lt]

